// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function replicate_DNA(param) {
  if (param >= 71) {
    if (param >= 84) {
      return /* A */65;
    } else {
      return /* C */67;
    }
  } else if (param >= 67) {
    return /* G */71;
  } else {
    return /* T */84;
  }
}

function replicate_RNA(param) {
  if (param >= 71) {
    if (param >= 85) {
      return /* A */65;
    } else {
      return /* C */67;
    }
  } else if (param >= 67) {
    return /* G */71;
  } else {
    return /* U */85;
  }
}

function transcribe(param) {
  if (param >= 71) {
    if (param >= 84) {
      return /* A */65;
    } else {
      return /* C */67;
    }
  } else if (param >= 67) {
    return /* G */71;
  } else {
    return /* U */85;
  }
}

function reverse_transcribe(param) {
  if (param >= 71) {
    if (param >= 85) {
      return /* A */65;
    } else {
      return /* C */67;
    }
  } else if (param >= 67) {
    return /* G */71;
  } else {
    return /* T */84;
  }
}

function to_dna(param) {
  switch (param) {
    case "A" :
        return /* A */65;
    case "C" :
        return /* C */67;
    case "G" :
        return /* G */71;
    case "T" :
        return /* T */84;
    default:
      return ;
  }
}

function to_rna(param) {
  switch (param) {
    case "A" :
        return /* A */65;
    case "C" :
        return /* C */67;
    case "G" :
        return /* G */71;
    case "U" :
        return /* U */85;
    default:
      return ;
  }
}

function to_string(param) {
  if (param !== 67) {
    if (param >= 84) {
      if (param >= 85) {
        return "U";
      } else {
        return "T";
      }
    } else if (param >= 71) {
      return "G";
    } else {
      return "A";
    }
  } else {
    return "C";
  }
}

function parse_dna(f, letter) {
  return Belt_Option.map(to_dna(letter), f);
}

function parse_rna(f, letter) {
  return Belt_Option.map(to_rna(letter), f);
}

function display_transcription(letter) {
  var match = Belt_Option.map(to_dna(letter), transcribe);
  if (match !== undefined) {
    return to_string(match);
  } else {
    return "";
  }
}

function display_replication(letter) {
  var match = Belt_Option.map(to_dna(letter), replicate_DNA);
  if (match !== undefined) {
    return to_string(match);
  } else {
    return "";
  }
}

exports.replicate_DNA = replicate_DNA;
exports.replicate_RNA = replicate_RNA;
exports.transcribe = transcribe;
exports.reverse_transcribe = reverse_transcribe;
exports.to_dna = to_dna;
exports.to_rna = to_rna;
exports.to_string = to_string;
exports.parse_dna = parse_dna;
exports.parse_rna = parse_rna;
exports.display_transcription = display_transcription;
exports.display_replication = display_replication;
/* No side effect */
